# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/assurance
spring.datasource.username=antonin
spring.datasource.password=123123

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update

# Dev only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Performance
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# UUID
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# HIKARI (pool)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000